import type { Metadata } from "next";
import { Roboto, Tektur } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const roboto = Roboto({
  variable: "--font_roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  style: ["italic", "normal"]
});

const tektur = Tektur({
  variable: "--font_tektur",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Chad Jones Portfolio - Data Analyst",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${tektur.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
